# Generated by Django 4.0.4 on 2022-04-20 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data',
            field=models.DateField(auto_now=True),
        ),
    ]
